# Generated by Django 2.0.5 on 2018-05-29 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180529_1019'),
        ('users', '0006_message_drinks'),
    ]

    operations = [
    ]
