<<<<<<< HEAD
# Generated by Django 2.0.5 on 2018-05-30 15:32
=======
# Generated by Django 2.0.5 on 2018-05-30 02:27
>>>>>>> ca9c0ee435d0ca79987a93a1b7e8db872e4808a2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20180529_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='drinks',
        ),
    ]
